CREATE OR REPLACE TABLE CUSTOMER_DATA (
    CUSTOMER_NUMBER STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    BIRTHDATE DATE,
    SSN STRING,
    CUSTOMER_ADDRESS_STREET STRING,
    CUSTOMER_ADDRESS_HOUSE_NUMBER STRING,
    CUSTOMER_ADDRESS_CITY STRING,
    CUSTOMER_ADDRESS_STATE STRING,
    CUSTOMER_ADDRESS_COUNTRY STRING,
    CUSTOMER_ADDRESS_ZIP_CODE STRING,
    CREDITCARD_NUMBER STRING,
    CREDITCARD_EXPIRATION_DATE STRING,
    CREDITCARD_VERIFICATION_CODE STRING,
    CREDITCARD_PROVIDER STRING
) USING delta PARTITIONED BY (BIRTHDATE);

CREATE OR REPLACE TABLE CREDITCARD_TRANSACTION (
    TRANSACTION_ID STRING,
    CUSTOMER_NUMBER STRING,
    TRANSACTION_VALUE FLOAT,
    TRANSACTION_DATE_TIME TIMESTAMP,
    NUMBER_OF_ITEMS INT
) USING delta PARTITIONED BY (TRANSACTION_DATE_TIME);

CREATE OR REPLACE TABLE PRODUCT_TRANSACTION (
    TRANSACTION_ID STRING,
    ITEM_EAN STRING,
    ITEM_DEPARTMENT STRING,
    ITEM_VALUE FLOAT,
    ITEM_ID STRING,
    ITEM_QUANTITY INT) 